# Generated by Django 6.0.5 on 2026-07-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('postcosecha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('codigo_liquidacion', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_liquidacion', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('documento_proveedor', models.FileField(blank=True, null=True, upload_to='liquidaciones/documentos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('ESTANDAR', 'Estándar')], max_length=10)),
                ('cantidad_tallos', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarifario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postcosecha.tarifario')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.variedad')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.liquidacion')),
            ],
        ),
    ]
