# Generated by Django 6.0.5 on 2026-07-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('codigo_clasificacion', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_clasificacion', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_mallas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CLASIFICACION', 'En clasificación'), ('CLASIFICADA', 'Clasificada')], default='PENDIENTE', max_length=20)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.variedad')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_mallas_procesadas', models.PositiveIntegerField()),
                ('largo', models.CharField(choices=[('OPTIMO', 'Óptimo'), ('ESTANDAR', 'Estándar')], max_length=10)),
                ('tallos_exportables', models.PositiveIntegerField()),
                ('tallos_nacionales', models.PositiveIntegerField(default=0)),
                ('tallos_sobrantes', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcosecha.clasificacion')),
                ('detalle_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postcosecha.detallerecepcion')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('codigo_recepcion', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('numero_recepcion', models.PositiveIntegerField(unique=True)),
                ('fecha_recepcion', models.DateTimeField()),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.finca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcosecha.recepcion'),
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('codigo_tarifario', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('precio_optimo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_estandar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.variedad')),
            ],
        ),
    ]
