from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.iniciarSesion, name='login'),
    path('recuperar-acceso/', views.solicitarRecuperacion, name='recuperarCredenciales'),
    path('recuperar-acceso/enviado/', views.recuperacionEnviada, name='recuperarCredencialesEnviado'),
    path(
        'restablecer-acceso/<uidb64>/<token>/',
        views.RestablecerCredencialView.as_view(),
        name='restablecerCredencial',
    ),
    path(
        'restablecer-acceso/completado/',
        views.restablecimientoCompleto,
        name='restablecerCredencialCompleto',
    ),
    path('logout/', views.cerrarSesion, name='logout'),
    path('usuarios/', views.inicioUsuario, name='inicioUsuario'),
    path('usuarios/nuevo/', views.nuevoUsuario, name='nuevoUsuario'),
    path('usuarios/guardar/', views.guardarUsuario, name='guardarUsuario'),
    path('usuarios/editar/<int:id>/', views.editarUsuario, name='editarUsuario'),
    path('usuarios/procesar/', views.procesarUsuario, name='procesarUsuario'),
    path('proveedores/', views.inicioProveedor, name='inicioProveedor'),
    path('proveedores/nuevo/', views.nuevoProveedor, name='nuevoProveedor'),
    path('proveedores/guardar/', views.guardarProveedor, name='guardarProveedor'),
    path('proveedores/editar/<str:codigo>/', views.editarProveedor, name='editarProveedor'),
    path('proveedores/procesar-edicion/', views.procesarEdicionProveedor, name='procesarEdicionProveedor'),
    path('proveedores/estado/<str:codigo>/', views.cambiarEstadoProveedor, name='cambiarEstadoProveedor'),
    path('variedades/', views.inicioVariedad, name='inicioVariedad'),
    path('variedades/nueva/', views.nuevaVariedad, name='nuevaVariedad'),
    path('variedades/guardar/', views.guardarVariedad, name='guardarVariedad'),
    path('variedades/editar/<str:codigo>/', views.editarVariedad, name='editarVariedad'),
    path('variedades/procesar-edicion/', views.procesarEdicionVariedad, name='procesarEdicionVariedad'),
    path('variedades/estado/<str:codigo>/', views.cambiarEstadoVariedad, name='cambiarEstadoVariedad'),
    path('fincas/', views.inicioFinca, name='inicioFinca'),
    path('fincas/nueva/', views.nuevaFinca, name='nuevaFinca'),
    path('fincas/guardar/', views.guardarFinca, name='guardarFinca'),
    path('fincas/editar/<str:codigo>/', views.editarFinca, name='editarFinca'),
    path('fincas/procesar-edicion/', views.procesarEdicionFinca, name='procesarEdicionFinca'),
    path('fincas/estado/<str:codigo>/', views.cambiarEstadoFinca, name='cambiarEstadoFinca'),
    path('personal/', views.inicioPersonal, name='inicioPersonal'),
    path('personal/nuevo/', views.nuevoPersonal, name='nuevoPersonal'),
    path('personal/guardar/', views.guardarPersonal, name='guardarPersonal'),
    path('personal/editar/<str:codigo>/', views.editarPersonal, name='editarPersonal'),
    path('personal/procesar-edicion/', views.procesarEdicionPersonal, name='procesarEdicionPersonal'),
    path('personal/estado/<str:codigo>/', views.cambiarEstadoPersonal, name='cambiarEstadoPersonal'),
    path('personal/<str:codigo>/expediente/', views.expedientePersonal, name='expedientePersonal'),
    path('personal/<str:codigo>/permisos/guardar/', views.guardarPermisoPersonal, name='guardarPermisoPersonal'),
    path('personal/<str:codigo>/vacaciones/guardar/', views.guardarVacacionPersonal, name='guardarVacacionPersonal'),
    path('personal/<str:codigo>/documentos/guardar/', views.guardarDocumentoPersonal, name='guardarDocumentoPersonal'),
]
