# Generated by Django 6.0.5 on 2026-07-30 20:55

import FlorLY.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_validar_archivos_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedad',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='variedades/imagenes/', validators=[FlorLY.file_security.validate_image]),
        ),
    ]
