--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administracion_documentopersonal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_documentopersonal (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    archivo character varying(100) NOT NULL,
    observacion text NOT NULL,
    fecha_documento date NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    personal_id character varying(10) NOT NULL
);


--
-- Name: administracion_documentopersonal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administracion_documentopersonal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administracion_documentopersonal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administracion_finca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_finca (
    codigo_finca character varying(10) NOT NULL,
    nombre character varying(100) NOT NULL,
    ubicacion character varying(200) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: administracion_permisopersonal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_permisopersonal (
    id bigint NOT NULL,
    motivo character varying(30) NOT NULL,
    observacion text NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date NOT NULL,
    hora_salida time without time zone,
    hora_retorno time without time zone,
    dias_descontados numeric(7,2) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    personal_id character varying(10) NOT NULL
);


--
-- Name: administracion_permisopersonal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administracion_permisopersonal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administracion_permisopersonal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administracion_personal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_personal (
    codigo_personal character varying(10) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    cedula character varying(10) NOT NULL,
    telefono character varying(15) NOT NULL,
    fecha_ingreso date NOT NULL,
    area character varying(100) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    finca_id character varying(10) NOT NULL
);


--
-- Name: administracion_proveedor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_proveedor (
    codigo_proveedor character varying(10) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    cedula_ruc character varying(13) NOT NULL,
    telefono character varying(15) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: administracion_vacacionpersonal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_vacacionpersonal (
    id bigint NOT NULL,
    fecha_desde date NOT NULL,
    fecha_hasta date NOT NULL,
    dias_tomados integer NOT NULL,
    observacion text NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    personal_id character varying(10) NOT NULL,
    CONSTRAINT administracion_vacacionpersonal_dias_tomados_check CHECK ((dias_tomados >= 0))
);


--
-- Name: administracion_vacacionpersonal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.administracion_vacacionpersonal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.administracion_vacacionpersonal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administracion_variedad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administracion_variedad (
    codigo_variedad character varying(10) NOT NULL,
    nombre character varying(100) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: auditoria_bitacora; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_bitacora (
    id bigint NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    accion character varying(100) NOT NULL,
    tabla_afectada character varying(100) NOT NULL,
    codigo_registro character varying(20) NOT NULL,
    descripcion text NOT NULL,
    direccion_ip inet,
    usuario_id integer NOT NULL
);


--
-- Name: auditoria_bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_bitacora ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: inventario_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_categoria (
    codigo_categoria character varying(10) NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: inventario_detalleentrada; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_detalleentrada (
    id bigint NOT NULL,
    tipo_presentacion character varying(100) NOT NULL,
    contenido_presentacion numeric(12,2) NOT NULL,
    cantidad_envases integer NOT NULL,
    cantidad_ingresada numeric(12,2) NOT NULL,
    entrada_id character varying(12) NOT NULL,
    producto_id character varying(10) NOT NULL,
    CONSTRAINT inventario_detalleentrada_cantidad_envases_check CHECK ((cantidad_envases >= 0))
);


--
-- Name: inventario_detalleentrada_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventario_detalleentrada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_detalleentrada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_detallesalida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_detallesalida (
    id bigint NOT NULL,
    cantidad_salida numeric(12,2) NOT NULL,
    producto_id character varying(10) NOT NULL,
    salida_id character varying(12) NOT NULL
);


--
-- Name: inventario_detallesalida_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventario_detallesalida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_detallesalida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario_entrada; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_entrada (
    codigo_entrada character varying(12) NOT NULL,
    fecha_entrada date NOT NULL,
    numero_factura character varying(50) NOT NULL,
    observacion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    proveedor_insumo_id character varying(12) NOT NULL
);


--
-- Name: inventario_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_producto (
    codigo_producto character varying(10) NOT NULL,
    nombre character varying(150) NOT NULL,
    marca character varying(100) NOT NULL,
    existencia_actual numeric(12,2) NOT NULL,
    stock_minimo numeric(12,2) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    categoria_id character varying(10) NOT NULL,
    unidad_medida_id character varying(10) NOT NULL
);


--
-- Name: inventario_proveedorinsumo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_proveedorinsumo (
    codigo_proveedor_insumo character varying(12) NOT NULL,
    nombre_contacto character varying(200) NOT NULL,
    nombre_empresa character varying(200) NOT NULL,
    telefono character varying(15) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: inventario_salida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_salida (
    codigo_salida character varying(12) NOT NULL,
    fecha_salida date NOT NULL,
    destino character varying(150) NOT NULL,
    motivo character varying(200) NOT NULL,
    observacion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    finca_id character varying(10) NOT NULL
);


--
-- Name: inventario_unidadmedida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventario_unidadmedida (
    codigo_unidad_medida character varying(10) NOT NULL,
    nombre character varying(100) NOT NULL,
    abreviatura character varying(20) NOT NULL,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


--
-- Name: liquidaciones_detalleliquidacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.liquidaciones_detalleliquidacion (
    id bigint NOT NULL,
    calidad character varying(10) NOT NULL,
    cantidad_tallos integer NOT NULL,
    valor_unitario numeric(10,4) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    tarifario_id character varying(12) NOT NULL,
    variedad_id character varying(10) NOT NULL,
    liquidacion_id character varying(12) NOT NULL,
    CONSTRAINT liquidaciones_detalleliquidacion_cantidad_tallos_check CHECK ((cantidad_tallos >= 0))
);


--
-- Name: liquidaciones_detalleliquidacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.liquidaciones_detalleliquidacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.liquidaciones_detalleliquidacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liquidaciones_liquidacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.liquidaciones_liquidacion (
    codigo_liquidacion character varying(12) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    fecha_liquidacion date NOT NULL,
    total numeric(12,2) NOT NULL,
    documento_proveedor character varying(100),
    estado character varying(10) NOT NULL,
    observacion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    proveedor_id character varying(10) NOT NULL
);


--
-- Name: postcosecha_clasificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcosecha_clasificacion (
    codigo_clasificacion character varying(12) NOT NULL,
    fecha_clasificacion date NOT NULL,
    observacion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    recepcion_id character varying(12)
);


--
-- Name: postcosecha_detalleclasificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcosecha_detalleclasificacion (
    id bigint NOT NULL,
    cantidad_mallas_procesadas integer NOT NULL,
    largo character varying(10) NOT NULL,
    tallos_exportables integer NOT NULL,
    tallos_nacionales integer NOT NULL,
    tallos_sobrantes integer NOT NULL,
    observacion text NOT NULL,
    clasificacion_id character varying(12) NOT NULL,
    detalle_recepcion_id bigint NOT NULL,
    CONSTRAINT postcosecha_detalleclasificaci_cantidad_mallas_procesadas_check CHECK ((cantidad_mallas_procesadas >= 0)),
    CONSTRAINT postcosecha_detalleclasificacion_tallos_exportables_check CHECK ((tallos_exportables >= 0)),
    CONSTRAINT postcosecha_detalleclasificacion_tallos_nacionales_check CHECK ((tallos_nacionales >= 0)),
    CONSTRAINT postcosecha_detalleclasificacion_tallos_sobrantes_check CHECK ((tallos_sobrantes >= 0))
);


--
-- Name: postcosecha_detalleclasificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.postcosecha_detalleclasificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postcosecha_detalleclasificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postcosecha_detallerecepcion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcosecha_detallerecepcion (
    id bigint NOT NULL,
    cantidad_mallas integer NOT NULL,
    estado character varying(20) NOT NULL,
    variedad_id character varying(10) NOT NULL,
    recepcion_id character varying(12) NOT NULL,
    tallos_por_malla integer NOT NULL,
    CONSTRAINT postcosecha_detallerecepcion_cantidad_mallas_check CHECK ((cantidad_mallas >= 0)),
    CONSTRAINT postcosecha_detallerecepcion_tallos_por_malla_check CHECK ((tallos_por_malla >= 0))
);


--
-- Name: postcosecha_detallerecepcion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.postcosecha_detallerecepcion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postcosecha_detallerecepcion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: postcosecha_recepcion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcosecha_recepcion (
    codigo_recepcion character varying(12) NOT NULL,
    numero_recepcion integer NOT NULL,
    fecha_recepcion timestamp with time zone NOT NULL,
    observacion text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    finca_id character varying(10),
    proveedor_id character varying(10),
    empleado_receptor_id character varying(10),
    CONSTRAINT postcosecha_recepcion_numero_recepcion_check CHECK ((numero_recepcion >= 0))
);


--
-- Name: postcosecha_tarifario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcosecha_tarifario (
    codigo_tarifario character varying(12) NOT NULL,
    precio_optimo numeric(10,4) NOT NULL,
    precio_estandar numeric(10,4) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    estado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    variedad_id character varying(10) NOT NULL
);


--
-- Name: administracion_documentopersonal administracion_documentopersonal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_documentopersonal
    ADD CONSTRAINT administracion_documentopersonal_pkey PRIMARY KEY (id);


--
-- Name: administracion_finca administracion_finca_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_finca
    ADD CONSTRAINT administracion_finca_nombre_key UNIQUE (nombre);


--
-- Name: administracion_finca administracion_finca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_finca
    ADD CONSTRAINT administracion_finca_pkey PRIMARY KEY (codigo_finca);


--
-- Name: administracion_permisopersonal administracion_permisopersonal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_permisopersonal
    ADD CONSTRAINT administracion_permisopersonal_pkey PRIMARY KEY (id);


--
-- Name: administracion_personal administracion_personal_cedula_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_personal
    ADD CONSTRAINT administracion_personal_cedula_key UNIQUE (cedula);


--
-- Name: administracion_personal administracion_personal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_personal
    ADD CONSTRAINT administracion_personal_pkey PRIMARY KEY (codigo_personal);


--
-- Name: administracion_proveedor administracion_proveedor_cedula_ruc_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_proveedor
    ADD CONSTRAINT administracion_proveedor_cedula_ruc_key UNIQUE (cedula_ruc);


--
-- Name: administracion_proveedor administracion_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_proveedor
    ADD CONSTRAINT administracion_proveedor_pkey PRIMARY KEY (codigo_proveedor);


--
-- Name: administracion_vacacionpersonal administracion_vacacionpersonal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_vacacionpersonal
    ADD CONSTRAINT administracion_vacacionpersonal_pkey PRIMARY KEY (id);


--
-- Name: administracion_variedad administracion_variedad_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_variedad
    ADD CONSTRAINT administracion_variedad_nombre_key UNIQUE (nombre);


--
-- Name: administracion_variedad administracion_variedad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_variedad
    ADD CONSTRAINT administracion_variedad_pkey PRIMARY KEY (codigo_variedad);


--
-- Name: auditoria_bitacora auditoria_bitacora_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_bitacora
    ADD CONSTRAINT auditoria_bitacora_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inventario_categoria inventario_categoria_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_categoria
    ADD CONSTRAINT inventario_categoria_nombre_key UNIQUE (nombre);


--
-- Name: inventario_categoria inventario_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_categoria
    ADD CONSTRAINT inventario_categoria_pkey PRIMARY KEY (codigo_categoria);


--
-- Name: inventario_detalleentrada inventario_detalleentrada_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detalleentrada
    ADD CONSTRAINT inventario_detalleentrada_pkey PRIMARY KEY (id);


--
-- Name: inventario_detallesalida inventario_detallesalida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detallesalida
    ADD CONSTRAINT inventario_detallesalida_pkey PRIMARY KEY (id);


--
-- Name: inventario_entrada inventario_entrada_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_entrada
    ADD CONSTRAINT inventario_entrada_pkey PRIMARY KEY (codigo_entrada);


--
-- Name: inventario_producto inventario_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_producto
    ADD CONSTRAINT inventario_producto_pkey PRIMARY KEY (codigo_producto);


--
-- Name: inventario_proveedorinsumo inventario_proveedorinsumo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_proveedorinsumo
    ADD CONSTRAINT inventario_proveedorinsumo_pkey PRIMARY KEY (codigo_proveedor_insumo);


--
-- Name: inventario_salida inventario_salida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_salida
    ADD CONSTRAINT inventario_salida_pkey PRIMARY KEY (codigo_salida);


--
-- Name: inventario_unidadmedida inventario_unidadmedida_abreviatura_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_unidadmedida
    ADD CONSTRAINT inventario_unidadmedida_abreviatura_key UNIQUE (abreviatura);


--
-- Name: inventario_unidadmedida inventario_unidadmedida_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_unidadmedida
    ADD CONSTRAINT inventario_unidadmedida_nombre_key UNIQUE (nombre);


--
-- Name: inventario_unidadmedida inventario_unidadmedida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_unidadmedida
    ADD CONSTRAINT inventario_unidadmedida_pkey PRIMARY KEY (codigo_unidad_medida);


--
-- Name: liquidaciones_detalleliquidacion liquidaciones_detalleliquidacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_detalleliquidacion
    ADD CONSTRAINT liquidaciones_detalleliquidacion_pkey PRIMARY KEY (id);


--
-- Name: liquidaciones_liquidacion liquidaciones_liquidacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_liquidacion
    ADD CONSTRAINT liquidaciones_liquidacion_pkey PRIMARY KEY (codigo_liquidacion);


--
-- Name: postcosecha_clasificacion postcosecha_clasificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_clasificacion
    ADD CONSTRAINT postcosecha_clasificacion_pkey PRIMARY KEY (codigo_clasificacion);


--
-- Name: postcosecha_clasificacion postcosecha_clasificacion_recepcion_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_clasificacion
    ADD CONSTRAINT postcosecha_clasificacion_recepcion_id_key UNIQUE (recepcion_id);


--
-- Name: postcosecha_detalleclasificacion postcosecha_detalleclasificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detalleclasificacion
    ADD CONSTRAINT postcosecha_detalleclasificacion_pkey PRIMARY KEY (id);


--
-- Name: postcosecha_detallerecepcion postcosecha_detallerecepcion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detallerecepcion
    ADD CONSTRAINT postcosecha_detallerecepcion_pkey PRIMARY KEY (id);


--
-- Name: postcosecha_recepcion postcosecha_recepcion_numero_recepcion_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_recepcion
    ADD CONSTRAINT postcosecha_recepcion_numero_recepcion_key UNIQUE (numero_recepcion);


--
-- Name: postcosecha_recepcion postcosecha_recepcion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_recepcion
    ADD CONSTRAINT postcosecha_recepcion_pkey PRIMARY KEY (codigo_recepcion);


--
-- Name: postcosecha_tarifario postcosecha_tarifario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_tarifario
    ADD CONSTRAINT postcosecha_tarifario_pkey PRIMARY KEY (codigo_tarifario);


--
-- Name: administracion_documentopersonal_personal_id_216522e4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_documentopersonal_personal_id_216522e4 ON public.administracion_documentopersonal USING btree (personal_id);


--
-- Name: administracion_documentopersonal_personal_id_216522e4_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_documentopersonal_personal_id_216522e4_like ON public.administracion_documentopersonal USING btree (personal_id varchar_pattern_ops);


--
-- Name: administracion_finca_codigo_finca_f5c8599d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_finca_codigo_finca_f5c8599d_like ON public.administracion_finca USING btree (codigo_finca varchar_pattern_ops);


--
-- Name: administracion_finca_nombre_c6cc17f1_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_finca_nombre_c6cc17f1_like ON public.administracion_finca USING btree (nombre varchar_pattern_ops);


--
-- Name: administracion_permisopersonal_personal_id_0d67df0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_permisopersonal_personal_id_0d67df0e ON public.administracion_permisopersonal USING btree (personal_id);


--
-- Name: administracion_permisopersonal_personal_id_0d67df0e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_permisopersonal_personal_id_0d67df0e_like ON public.administracion_permisopersonal USING btree (personal_id varchar_pattern_ops);


--
-- Name: administracion_personal_cedula_f4bbe1cf_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_personal_cedula_f4bbe1cf_like ON public.administracion_personal USING btree (cedula varchar_pattern_ops);


--
-- Name: administracion_personal_codigo_personal_690f8895_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_personal_codigo_personal_690f8895_like ON public.administracion_personal USING btree (codigo_personal varchar_pattern_ops);


--
-- Name: administracion_personal_finca_id_de6d9f39; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_personal_finca_id_de6d9f39 ON public.administracion_personal USING btree (finca_id);


--
-- Name: administracion_personal_finca_id_de6d9f39_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_personal_finca_id_de6d9f39_like ON public.administracion_personal USING btree (finca_id varchar_pattern_ops);


--
-- Name: administracion_proveedor_cedula_ruc_bccd406f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_proveedor_cedula_ruc_bccd406f_like ON public.administracion_proveedor USING btree (cedula_ruc varchar_pattern_ops);


--
-- Name: administracion_proveedor_codigo_proveedor_8aca6696_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_proveedor_codigo_proveedor_8aca6696_like ON public.administracion_proveedor USING btree (codigo_proveedor varchar_pattern_ops);


--
-- Name: administracion_vacacionpersonal_personal_id_ff011689; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_vacacionpersonal_personal_id_ff011689 ON public.administracion_vacacionpersonal USING btree (personal_id);


--
-- Name: administracion_vacacionpersonal_personal_id_ff011689_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_vacacionpersonal_personal_id_ff011689_like ON public.administracion_vacacionpersonal USING btree (personal_id varchar_pattern_ops);


--
-- Name: administracion_variedad_codigo_variedad_dcd584ab_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_variedad_codigo_variedad_dcd584ab_like ON public.administracion_variedad USING btree (codigo_variedad varchar_pattern_ops);


--
-- Name: administracion_variedad_nombre_e1923dbb_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX administracion_variedad_nombre_e1923dbb_like ON public.administracion_variedad USING btree (nombre varchar_pattern_ops);


--
-- Name: auditoria_bitacora_usuario_id_81557f2e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_bitacora_usuario_id_81557f2e ON public.auditoria_bitacora USING btree (usuario_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inventario_categoria_codigo_categoria_2225716c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_categoria_codigo_categoria_2225716c_like ON public.inventario_categoria USING btree (codigo_categoria varchar_pattern_ops);


--
-- Name: inventario_categoria_nombre_df3900f0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_categoria_nombre_df3900f0_like ON public.inventario_categoria USING btree (nombre varchar_pattern_ops);


--
-- Name: inventario_detalleentrada_entrada_id_dff09998; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detalleentrada_entrada_id_dff09998 ON public.inventario_detalleentrada USING btree (entrada_id);


--
-- Name: inventario_detalleentrada_entrada_id_dff09998_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detalleentrada_entrada_id_dff09998_like ON public.inventario_detalleentrada USING btree (entrada_id varchar_pattern_ops);


--
-- Name: inventario_detalleentrada_producto_id_85f429c5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detalleentrada_producto_id_85f429c5 ON public.inventario_detalleentrada USING btree (producto_id);


--
-- Name: inventario_detalleentrada_producto_id_85f429c5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detalleentrada_producto_id_85f429c5_like ON public.inventario_detalleentrada USING btree (producto_id varchar_pattern_ops);


--
-- Name: inventario_detallesalida_producto_id_dc7e977d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detallesalida_producto_id_dc7e977d ON public.inventario_detallesalida USING btree (producto_id);


--
-- Name: inventario_detallesalida_producto_id_dc7e977d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detallesalida_producto_id_dc7e977d_like ON public.inventario_detallesalida USING btree (producto_id varchar_pattern_ops);


--
-- Name: inventario_detallesalida_salida_id_7cb49c6a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detallesalida_salida_id_7cb49c6a ON public.inventario_detallesalida USING btree (salida_id);


--
-- Name: inventario_detallesalida_salida_id_7cb49c6a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_detallesalida_salida_id_7cb49c6a_like ON public.inventario_detallesalida USING btree (salida_id varchar_pattern_ops);


--
-- Name: inventario_entrada_codigo_entrada_6de97405_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_entrada_codigo_entrada_6de97405_like ON public.inventario_entrada USING btree (codigo_entrada varchar_pattern_ops);


--
-- Name: inventario_entrada_proveedor_insumo_id_617dd34a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_entrada_proveedor_insumo_id_617dd34a ON public.inventario_entrada USING btree (proveedor_insumo_id);


--
-- Name: inventario_entrada_proveedor_insumo_id_617dd34a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_entrada_proveedor_insumo_id_617dd34a_like ON public.inventario_entrada USING btree (proveedor_insumo_id varchar_pattern_ops);


--
-- Name: inventario_producto_categoria_id_7033fb47; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_producto_categoria_id_7033fb47 ON public.inventario_producto USING btree (categoria_id);


--
-- Name: inventario_producto_categoria_id_7033fb47_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_producto_categoria_id_7033fb47_like ON public.inventario_producto USING btree (categoria_id varchar_pattern_ops);


--
-- Name: inventario_producto_codigo_producto_77299917_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_producto_codigo_producto_77299917_like ON public.inventario_producto USING btree (codigo_producto varchar_pattern_ops);


--
-- Name: inventario_producto_unidad_medida_id_907f2948; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_producto_unidad_medida_id_907f2948 ON public.inventario_producto USING btree (unidad_medida_id);


--
-- Name: inventario_producto_unidad_medida_id_907f2948_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_producto_unidad_medida_id_907f2948_like ON public.inventario_producto USING btree (unidad_medida_id varchar_pattern_ops);


--
-- Name: inventario_proveedorinsu_codigo_proveedor_insumo_de714855_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_proveedorinsu_codigo_proveedor_insumo_de714855_like ON public.inventario_proveedorinsumo USING btree (codigo_proveedor_insumo varchar_pattern_ops);


--
-- Name: inventario_salida_codigo_salida_33248066_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_salida_codigo_salida_33248066_like ON public.inventario_salida USING btree (codigo_salida varchar_pattern_ops);


--
-- Name: inventario_salida_finca_id_1023a109; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_salida_finca_id_1023a109 ON public.inventario_salida USING btree (finca_id);


--
-- Name: inventario_salida_finca_id_1023a109_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_salida_finca_id_1023a109_like ON public.inventario_salida USING btree (finca_id varchar_pattern_ops);


--
-- Name: inventario_unidadmedida_abreviatura_40ea8b66_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_unidadmedida_abreviatura_40ea8b66_like ON public.inventario_unidadmedida USING btree (abreviatura varchar_pattern_ops);


--
-- Name: inventario_unidadmedida_codigo_unidad_medida_bf2db905_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_unidadmedida_codigo_unidad_medida_bf2db905_like ON public.inventario_unidadmedida USING btree (codigo_unidad_medida varchar_pattern_ops);


--
-- Name: inventario_unidadmedida_nombre_0cc2ea5c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventario_unidadmedida_nombre_0cc2ea5c_like ON public.inventario_unidadmedida USING btree (nombre varchar_pattern_ops);


--
-- Name: liquidaciones_detalleliquidacion_liquidacion_id_5980e0f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_liquidacion_id_5980e0f2 ON public.liquidaciones_detalleliquidacion USING btree (liquidacion_id);


--
-- Name: liquidaciones_detalleliquidacion_liquidacion_id_5980e0f2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_liquidacion_id_5980e0f2_like ON public.liquidaciones_detalleliquidacion USING btree (liquidacion_id varchar_pattern_ops);


--
-- Name: liquidaciones_detalleliquidacion_tarifario_id_75df3689; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_tarifario_id_75df3689 ON public.liquidaciones_detalleliquidacion USING btree (tarifario_id);


--
-- Name: liquidaciones_detalleliquidacion_tarifario_id_75df3689_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_tarifario_id_75df3689_like ON public.liquidaciones_detalleliquidacion USING btree (tarifario_id varchar_pattern_ops);


--
-- Name: liquidaciones_detalleliquidacion_variedad_id_c2bb27c2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_variedad_id_c2bb27c2 ON public.liquidaciones_detalleliquidacion USING btree (variedad_id);


--
-- Name: liquidaciones_detalleliquidacion_variedad_id_c2bb27c2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_detalleliquidacion_variedad_id_c2bb27c2_like ON public.liquidaciones_detalleliquidacion USING btree (variedad_id varchar_pattern_ops);


--
-- Name: liquidaciones_liquidacion_codigo_liquidacion_57bc8533_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_liquidacion_codigo_liquidacion_57bc8533_like ON public.liquidaciones_liquidacion USING btree (codigo_liquidacion varchar_pattern_ops);


--
-- Name: liquidaciones_liquidacion_proveedor_id_5bf39f72; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_liquidacion_proveedor_id_5bf39f72 ON public.liquidaciones_liquidacion USING btree (proveedor_id);


--
-- Name: liquidaciones_liquidacion_proveedor_id_5bf39f72_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX liquidaciones_liquidacion_proveedor_id_5bf39f72_like ON public.liquidaciones_liquidacion USING btree (proveedor_id varchar_pattern_ops);


--
-- Name: postcosecha_clasificacion_codigo_clasificacion_def0ffdd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_clasificacion_codigo_clasificacion_def0ffdd_like ON public.postcosecha_clasificacion USING btree (codigo_clasificacion varchar_pattern_ops);


--
-- Name: postcosecha_clasificacion_recepcion_id_0a7b3437_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_clasificacion_recepcion_id_0a7b3437_like ON public.postcosecha_clasificacion USING btree (recepcion_id varchar_pattern_ops);


--
-- Name: postcosecha_detalleclasificacion_clasificacion_id_6fecdba5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detalleclasificacion_clasificacion_id_6fecdba5 ON public.postcosecha_detalleclasificacion USING btree (clasificacion_id);


--
-- Name: postcosecha_detalleclasificacion_clasificacion_id_6fecdba5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detalleclasificacion_clasificacion_id_6fecdba5_like ON public.postcosecha_detalleclasificacion USING btree (clasificacion_id varchar_pattern_ops);


--
-- Name: postcosecha_detalleclasificacion_detalle_recepcion_id_8143c309; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detalleclasificacion_detalle_recepcion_id_8143c309 ON public.postcosecha_detalleclasificacion USING btree (detalle_recepcion_id);


--
-- Name: postcosecha_detallerecepcion_recepcion_id_ed203533; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detallerecepcion_recepcion_id_ed203533 ON public.postcosecha_detallerecepcion USING btree (recepcion_id);


--
-- Name: postcosecha_detallerecepcion_recepcion_id_ed203533_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detallerecepcion_recepcion_id_ed203533_like ON public.postcosecha_detallerecepcion USING btree (recepcion_id varchar_pattern_ops);


--
-- Name: postcosecha_detallerecepcion_variedad_id_58736c3b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detallerecepcion_variedad_id_58736c3b ON public.postcosecha_detallerecepcion USING btree (variedad_id);


--
-- Name: postcosecha_detallerecepcion_variedad_id_58736c3b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_detallerecepcion_variedad_id_58736c3b_like ON public.postcosecha_detallerecepcion USING btree (variedad_id varchar_pattern_ops);


--
-- Name: postcosecha_recepcion_codigo_recepcion_744a9522_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_codigo_recepcion_744a9522_like ON public.postcosecha_recepcion USING btree (codigo_recepcion varchar_pattern_ops);


--
-- Name: postcosecha_recepcion_empleado_receptor_id_3f14e3cf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_empleado_receptor_id_3f14e3cf ON public.postcosecha_recepcion USING btree (empleado_receptor_id);


--
-- Name: postcosecha_recepcion_empleado_receptor_id_3f14e3cf_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_empleado_receptor_id_3f14e3cf_like ON public.postcosecha_recepcion USING btree (empleado_receptor_id varchar_pattern_ops);


--
-- Name: postcosecha_recepcion_finca_id_8a0a903d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_finca_id_8a0a903d ON public.postcosecha_recepcion USING btree (finca_id);


--
-- Name: postcosecha_recepcion_finca_id_8a0a903d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_finca_id_8a0a903d_like ON public.postcosecha_recepcion USING btree (finca_id varchar_pattern_ops);


--
-- Name: postcosecha_recepcion_proveedor_id_d8176f76; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_proveedor_id_d8176f76 ON public.postcosecha_recepcion USING btree (proveedor_id);


--
-- Name: postcosecha_recepcion_proveedor_id_d8176f76_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_recepcion_proveedor_id_d8176f76_like ON public.postcosecha_recepcion USING btree (proveedor_id varchar_pattern_ops);


--
-- Name: postcosecha_tarifario_codigo_tarifario_d7ed3fda_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_tarifario_codigo_tarifario_d7ed3fda_like ON public.postcosecha_tarifario USING btree (codigo_tarifario varchar_pattern_ops);


--
-- Name: postcosecha_tarifario_variedad_id_6ccdcea9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_tarifario_variedad_id_6ccdcea9 ON public.postcosecha_tarifario USING btree (variedad_id);


--
-- Name: postcosecha_tarifario_variedad_id_6ccdcea9_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcosecha_tarifario_variedad_id_6ccdcea9_like ON public.postcosecha_tarifario USING btree (variedad_id varchar_pattern_ops);


--
-- Name: administracion_documentopersonal administracion_docum_personal_id_216522e4_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_documentopersonal
    ADD CONSTRAINT administracion_docum_personal_id_216522e4_fk_administr FOREIGN KEY (personal_id) REFERENCES public.administracion_personal(codigo_personal) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: administracion_permisopersonal administracion_permi_personal_id_0d67df0e_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_permisopersonal
    ADD CONSTRAINT administracion_permi_personal_id_0d67df0e_fk_administr FOREIGN KEY (personal_id) REFERENCES public.administracion_personal(codigo_personal) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: administracion_personal administracion_perso_finca_id_de6d9f39_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_personal
    ADD CONSTRAINT administracion_perso_finca_id_de6d9f39_fk_administr FOREIGN KEY (finca_id) REFERENCES public.administracion_finca(codigo_finca) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: administracion_vacacionpersonal administracion_vacac_personal_id_ff011689_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administracion_vacacionpersonal
    ADD CONSTRAINT administracion_vacac_personal_id_ff011689_fk_administr FOREIGN KEY (personal_id) REFERENCES public.administracion_personal(codigo_personal) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditoria_bitacora auditoria_bitacora_usuario_id_81557f2e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_bitacora
    ADD CONSTRAINT auditoria_bitacora_usuario_id_81557f2e_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_detalleentrada inventario_detalleen_entrada_id_dff09998_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detalleentrada
    ADD CONSTRAINT inventario_detalleen_entrada_id_dff09998_fk_inventari FOREIGN KEY (entrada_id) REFERENCES public.inventario_entrada(codigo_entrada) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_detalleentrada inventario_detalleen_producto_id_85f429c5_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detalleentrada
    ADD CONSTRAINT inventario_detalleen_producto_id_85f429c5_fk_inventari FOREIGN KEY (producto_id) REFERENCES public.inventario_producto(codigo_producto) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_detallesalida inventario_detallesa_producto_id_dc7e977d_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detallesalida
    ADD CONSTRAINT inventario_detallesa_producto_id_dc7e977d_fk_inventari FOREIGN KEY (producto_id) REFERENCES public.inventario_producto(codigo_producto) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_detallesalida inventario_detallesa_salida_id_7cb49c6a_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_detallesalida
    ADD CONSTRAINT inventario_detallesa_salida_id_7cb49c6a_fk_inventari FOREIGN KEY (salida_id) REFERENCES public.inventario_salida(codigo_salida) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_entrada inventario_entrada_proveedor_insumo_id_617dd34a_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_entrada
    ADD CONSTRAINT inventario_entrada_proveedor_insumo_id_617dd34a_fk_inventari FOREIGN KEY (proveedor_insumo_id) REFERENCES public.inventario_proveedorinsumo(codigo_proveedor_insumo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_producto inventario_producto_categoria_id_7033fb47_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_producto
    ADD CONSTRAINT inventario_producto_categoria_id_7033fb47_fk_inventari FOREIGN KEY (categoria_id) REFERENCES public.inventario_categoria(codigo_categoria) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_producto inventario_producto_unidad_medida_id_907f2948_fk_inventari; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_producto
    ADD CONSTRAINT inventario_producto_unidad_medida_id_907f2948_fk_inventari FOREIGN KEY (unidad_medida_id) REFERENCES public.inventario_unidadmedida(codigo_unidad_medida) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventario_salida inventario_salida_finca_id_1023a109_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventario_salida
    ADD CONSTRAINT inventario_salida_finca_id_1023a109_fk_administr FOREIGN KEY (finca_id) REFERENCES public.administracion_finca(codigo_finca) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: liquidaciones_detalleliquidacion liquidaciones_detall_liquidacion_id_5980e0f2_fk_liquidaci; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_detalleliquidacion
    ADD CONSTRAINT liquidaciones_detall_liquidacion_id_5980e0f2_fk_liquidaci FOREIGN KEY (liquidacion_id) REFERENCES public.liquidaciones_liquidacion(codigo_liquidacion) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: liquidaciones_detalleliquidacion liquidaciones_detall_tarifario_id_75df3689_fk_postcosec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_detalleliquidacion
    ADD CONSTRAINT liquidaciones_detall_tarifario_id_75df3689_fk_postcosec FOREIGN KEY (tarifario_id) REFERENCES public.postcosecha_tarifario(codigo_tarifario) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: liquidaciones_detalleliquidacion liquidaciones_detall_variedad_id_c2bb27c2_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_detalleliquidacion
    ADD CONSTRAINT liquidaciones_detall_variedad_id_c2bb27c2_fk_administr FOREIGN KEY (variedad_id) REFERENCES public.administracion_variedad(codigo_variedad) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: liquidaciones_liquidacion liquidaciones_liquid_proveedor_id_5bf39f72_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.liquidaciones_liquidacion
    ADD CONSTRAINT liquidaciones_liquid_proveedor_id_5bf39f72_fk_administr FOREIGN KEY (proveedor_id) REFERENCES public.administracion_proveedor(codigo_proveedor) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_clasificacion postcosecha_clasific_recepcion_id_0a7b3437_fk_postcosec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_clasificacion
    ADD CONSTRAINT postcosecha_clasific_recepcion_id_0a7b3437_fk_postcosec FOREIGN KEY (recepcion_id) REFERENCES public.postcosecha_recepcion(codigo_recepcion) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_detalleclasificacion postcosecha_detallec_clasificacion_id_6fecdba5_fk_postcosec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detalleclasificacion
    ADD CONSTRAINT postcosecha_detallec_clasificacion_id_6fecdba5_fk_postcosec FOREIGN KEY (clasificacion_id) REFERENCES public.postcosecha_clasificacion(codigo_clasificacion) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_detalleclasificacion postcosecha_detallec_detalle_recepcion_id_8143c309_fk_postcosec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detalleclasificacion
    ADD CONSTRAINT postcosecha_detallec_detalle_recepcion_id_8143c309_fk_postcosec FOREIGN KEY (detalle_recepcion_id) REFERENCES public.postcosecha_detallerecepcion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_detallerecepcion postcosecha_detaller_recepcion_id_ed203533_fk_postcosec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detallerecepcion
    ADD CONSTRAINT postcosecha_detaller_recepcion_id_ed203533_fk_postcosec FOREIGN KEY (recepcion_id) REFERENCES public.postcosecha_recepcion(codigo_recepcion) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_detallerecepcion postcosecha_detaller_variedad_id_58736c3b_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_detallerecepcion
    ADD CONSTRAINT postcosecha_detaller_variedad_id_58736c3b_fk_administr FOREIGN KEY (variedad_id) REFERENCES public.administracion_variedad(codigo_variedad) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_recepcion postcosecha_recepcio_empleado_receptor_id_3f14e3cf_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_recepcion
    ADD CONSTRAINT postcosecha_recepcio_empleado_receptor_id_3f14e3cf_fk_administr FOREIGN KEY (empleado_receptor_id) REFERENCES public.administracion_personal(codigo_personal) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_recepcion postcosecha_recepcio_finca_id_8a0a903d_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_recepcion
    ADD CONSTRAINT postcosecha_recepcio_finca_id_8a0a903d_fk_administr FOREIGN KEY (finca_id) REFERENCES public.administracion_finca(codigo_finca) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_recepcion postcosecha_recepcio_proveedor_id_d8176f76_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_recepcion
    ADD CONSTRAINT postcosecha_recepcio_proveedor_id_d8176f76_fk_administr FOREIGN KEY (proveedor_id) REFERENCES public.administracion_proveedor(codigo_proveedor) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: postcosecha_tarifario postcosecha_tarifari_variedad_id_6ccdcea9_fk_administr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcosecha_tarifario
    ADD CONSTRAINT postcosecha_tarifari_variedad_id_6ccdcea9_fk_administr FOREIGN KEY (variedad_id) REFERENCES public.administracion_variedad(codigo_variedad) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

