# Generated by Django 6.0.5 on 2026-07-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo_categoria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('codigo_entrada', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInsumo',
            fields=[
                ('codigo_proveedor_insumo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('codigo_unidad_medida', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('abreviatura', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('existencia_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_presentacion', models.CharField(max_length=100)),
                ('contenido_presentacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_envases', models.PositiveIntegerField()),
                ('cantidad_ingresada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedorinsumo'),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('codigo_salida', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('destino', models.CharField(blank=True, max_length=150)),
                ('motivo', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.finca')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.salida')),
            ],
        ),
    ]
