from django.urls import path
from . import views

urlpatterns = [
    path('proveedores-insumos/', views.inicioProveedorInsumo, name='inicioProveedorInsumo'),
    path('proveedores-insumos/nuevo/', views.nuevoProveedorInsumo, name='nuevoProveedorInsumo'),
    path('proveedores-insumos/guardar/', views.guardarProveedorInsumo, name='guardarProveedorInsumo'),
    path('proveedores-insumos/editar/<str:codigo>/', views.editarProveedorInsumo, name='editarProveedorInsumo'),
    path('proveedores-insumos/procesar-edicion/', views.procesarEdicionProveedorInsumo, name='procesarEdicionProveedorInsumo'),
    path('proveedores-insumos/estado/<str:codigo>/', views.cambiarEstadoProveedorInsumo, name='cambiarEstadoProveedorInsumo'),
    path('categorias/', views.inicioCategoria, name='inicioCategoria'),
    path('categorias/nueva/', views.nuevaCategoria, name='nuevaCategoria'),
    path('categorias/guardar/', views.guardarCategoria, name='guardarCategoria'),
    path('categorias/editar/<str:codigo>/', views.editarCategoria, name='editarCategoria'),
    path('categorias/procesar-edicion/', views.procesarEdicionCategoria, name='procesarEdicionCategoria'),
    path('categorias/estado/<str:codigo>/', views.cambiarEstadoCategoria, name='cambiarEstadoCategoria'),
    path('unidades-medida/', views.inicioUnidadMedida, name='inicioUnidadMedida'),
    path('unidades-medida/nueva/', views.nuevaUnidadMedida, name='nuevaUnidadMedida'),
    path('unidades-medida/guardar/', views.guardarUnidadMedida, name='guardarUnidadMedida'),
    path('unidades-medida/guardar-rapida/', views.guardarUnidadMedidaRapida, name='guardarUnidadMedidaRapida'),
    path('unidades-medida/editar/<str:codigo>/', views.editarUnidadMedida, name='editarUnidadMedida'),
    path('unidades-medida/procesar-edicion/', views.procesarEdicionUnidadMedida, name='procesarEdicionUnidadMedida'),
    path('unidades-medida/estado/<str:codigo>/', views.cambiarEstadoUnidadMedida, name='cambiarEstadoUnidadMedida'),
    path('productos/', views.inicioProducto, name='inicioProducto'),
    path('productos/nuevo/', views.nuevoProducto, name='nuevoProducto'),
    path('productos/guardar/', views.guardarProducto, name='guardarProducto'),
    path('productos/editar/<str:codigo>/', views.editarProducto, name='editarProducto'),
    path('productos/procesar-edicion/', views.procesarEdicionProducto, name='procesarEdicionProducto'),
    path('productos/estado/<str:codigo>/', views.cambiarEstadoProducto, name='cambiarEstadoProducto'),
    path('entradas/', views.inicioEntrada, name='inicioEntrada'),
    path('entradas/nueva/', views.nuevaEntrada, name='nuevaEntrada'),
    path('entradas/guardar/', views.guardarEntrada, name='guardarEntrada'),
    path('entradas/ver/<str:codigo>/', views.verEntrada, name='verEntrada'),
    path('salidas/', views.inicioSalida, name='inicioSalida'),
    path('salidas/nueva/', views.nuevaSalida, name='nuevaSalida'),
    path('salidas/guardar/', views.guardarSalida, name='guardarSalida'),
    path('salidas/ver/<str:codigo>/', views.verSalida, name='verSalida'),
    path('movimientos/', views.historialMovimientos, name='historialMovimientos'),
]
